name: Build on push to main

on:
  push:
    branches: [ "main" ]

jobs:
  buildAndTest:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        
